import { Metadata } from "next";

export const metadata: Metadata = {
    title: "About Me - ldqs",
    description: "Generated by create next app",
};

export default function About() {
    const skills = [
        { name: "PHP / Laravel", level: 90 },
        { name: "JavaScript / TypeScript", level: 85 },
        { name: "Next.js / React", level: 80 },
        { name: "Frontend Design / TailwindCSS", level: 75 },
        { name: "REST API Integration", level: 70 },
        { name: "Deployment / Git", level: 65 },
    ];

    const education = [
        {
            degree: "Bachelor of Computer Science",
            school: "University of Greenwich",
            year: "2020 - 2025",
        }
    ];

    return (
        <div className="max-w-4xl mx-auto space-y-14">
            <h1 className="text-5xl font-bold text-center drop-shadow-xl">About Me</h1>

            <div className="p-10 rounded-2xl bg-base-100 backdrop-blur-xl border border-base-300 shadow-2xl shadow-black/40 transform hover:-translate-y-2 hover:shadow-[0_40px_80px_-20px_rgba(0,0,0,0.7)] transition-all duration-300">
                <h2 className="text-3xl font-semibold mb-3">Who I Am</h2>
                <p className="opacity-80 leading-relaxed text-lg">
                    I&apos;m <strong>Quang Sang Le Do</strong>, a full-stack web developer passionate about crafting modern, responsive websites. I specialize in building intuitive interfaces with <strong>Next.js</strong> and creating robust backend systems using <strong>Laravel</strong>, delivering seamless and engaging digital experiences.
                </p>
            </div>

            <div className="p-10 rounded-2xl bg-base-100 backdrop-blur-xl border border-base-300 shadow-2xl shadow-black/40 transform hover:-translate-y-2 hover:shadow-[0_40px_80px_-20px_rgba(0,0,0,0.7)] transition-all duration-300">
                <h2 className="text-3xl font-semibold mb-6">Education</h2>
                <div className="space-y-4">
                    {education.map((edu, i) => (
                        <div key={i} className="flex flex-col md:flex-row md:justify-between">
                            <span className="font-medium">{edu.degree}</span>
                            <span className="opacity-70">{edu.school}</span>
                            <span className="opacity-50">{edu.year}</span>
                        </div>
                    ))}
                </div>
            </div>

            <div className="p-10 rounded-2xl bg-base-100 backdrop-blur-xl border border-base-300 shadow-2xl shadow-black/40 transform hover:-translate-y-2 hover:shadow-[0_40px_80px_-20px_rgba(0,0,0,0.7)] transition-all duration-300">
                <h2 className="text-3xl font-semibold mb-6">Skills</h2>
                <div className="space-y-6">
                    {skills.map((skill, i) => (
                        <div key={i}>
                            <div className="flex justify-between mb-1 text-lg font-medium">
                                <span>{skill.name}</span>
                                <span>{skill.level}%</span>
                            </div>
                            <progress
                                className="progress progress-primary w-full h-4 bg-base-300 backdrop-blur-xl"
                                value={skill.level}
                                max={100}
                            ></progress>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
