import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Contact - ldqs",
    description: "Generated by create next app",
};

const links = [
    { title: "Email address", link: "mailto:itsldqs2103@gmail.com", content: "itsldqs2103@gmail.com" },
    { title: "GitHub", link: "https://github.com/itsldqs2103", content: "https://github.com/itsldqs2103" },
    { title: "X (formerly Twitter)", link: "https://x.com/itsldqs2103", content: "https://x.com/itsldqs2103" },
];

export default function Contact() {
    return (
        <div className="max-w-3xl mx-auto space-y-14">
            <h1 className="text-5xl font-bold text-center drop-shadow-xl mb-6">Contact</h1>
            <p className="opacity-80 text-center max-w-xl mx-auto text-lg">
                I&apos;d love to hear from you! Whether you have a project to discuss, want to collaborate, or just want to say hello, don’t hesitate to get in touch.
            </p>

            <div className="p-10 rounded-2xl bg-base-100 backdrop-blur-xl border border-base-300 shadow-2xl shadow-black/40 space-y-4 transform hover:-translate-y-2 hover:shadow-[0_40px_80px_-20px_rgba(0,0,0,0.7)] transition-[transform,translate,box-shadow]">
                {links.map((l, i) => (
                    <p key={i}>
                        <strong>{l.title}:</strong> <a href={l.link} className="link link-primary transition-[color]" target="_blank">{l.content}</a>
                    </p>
                ))}
            </div>
        </div>
    );
}