import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Projects - ldqs",
    description: "Generated by create next app",
};

export default function Projects() {
    const projects = [
        {
            name: "ldqs's Portfolio Website",
            desc: "A sleek, fully responsive portfolio with About Me, Projects, and Contact sections, built using Next.js, TailwindCSS, and DaisyUI.",
            demoUrl: "https://ldqs.vercel.app",
            status: "In Progress",
        }
    ];

    return (
        <div className="max-w-5xl mx-auto">
            <h1 className="text-5xl font-bold text-center mb-10 drop-shadow-xl">Projects</h1>

            {projects.length === 0 ? (
                <div className="text-center p-10 rounded-2xl bg-base-100 backdrop-blur-xl border border-base-300 shadow-2xl shadow-black/40 hover:shadow-[0_40px_80px_-20px_rgba(0,0,0,0.7)] transition-shadow">
                    <h2 className="text-3xl font-semibold mb-3">No Projects Found</h2>
                    <p className="opacity-80">There are currently no projects to display. Please check back later.</p>
                </div>
            ) : (
                <div className="grid gap-8 md:grid-cols-2">
                    {projects.map((p, i) => (
                        <div
                            key={i}
                            className="p-8 rounded-2xl bg-base-100 backdrop-blur-xl border border-base-300 shadow-2xl shadow-black/40 hover:shadow-[0_40px_80px_-20px_rgba(0,0,0,0.7)] transition-shadow"
                        >
                            <span
                                className={`inline-block px-3 py-1 rounded-full text-sm font-semibold mb-3 ${p.status === "Completed"
                                    ? "bg-green-500 text-white"
                                    : p.status === "In Progress"
                                        ? "bg-yellow-400 text-black"
                                        : "bg-gray-400 text-white"
                                    }`}
                            >
                                {p.status}
                            </span>

                            <h2 className="text-3xl font-semibold mb-3">{p.name}</h2>
                            <p className="opacity-80 mb-4">{p.desc}</p>
                            <a href={p.demoUrl} target="_blank" className="btn btn-primary w-full">Live Demo</a>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}
