import { Contact, Folder, User } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Home - ldqs",
  description: "Generated by create next app",
};

const cards = [
  { icon: User, title: "About Me", link: "/aboutme" },
  { icon: Folder, title: "Projects", link: "/projects" },
  { icon: Contact, title: "Contact", link: "/contact" },
];

export default function Home() {
  return (
    <div className="max-w-5xl mx-auto space-y-16">
      <section className="text-center">
        <h1 className="text-6xl font-extrabold mb-6 drop-shadow-lg">Welcome</h1>
        <p className="text-lg opacity-80 max-w-2xl mx-auto text-center">
          I&apos;m <strong>Quang Sang Le Do</strong>, a full-stack developer building modern, responsive websites with seamless user experiences.
        </p>
      </section>

      <section className="grid md:grid-cols-3 gap-8">

        {cards.map((item, i) => {
          const Icon = item.icon;
          return (
            <Link
              key={i}
              href={item.link}
              className="p-8 text-center rounded-2xl bg-base-100 backdrop-blur-xl border border-base-300 shadow-2xl shadow-black/40 transform hover:-translate-y-2 hover:shadow-[0_40px_80px_-20px_rgba(0,0,0,0.7)] transition-[transform,translate,box-shadow]"
            >
              <div className="flex flex-col items-center gap-3">
                <Icon className="h-8 w-8 text-primary" />
                <h3 className="text-2xl font-semibold">{item.title}</h3>
              </div>
            </Link>
          );
        })}
      </section>
    </div>
  );
}